title      = "Test Page"
url        = "http://localhost:4000/"
articleDir = "test-data/content/"
themeDir   = "test-data/theme/"
outputDir  = "test-data/public/"
localServerPort  = 4000

[[menu]]
name = "Index"
loc  = "/"
