name:                gcwdr
version:             0.3.0.0
github:              "u2x1/gcwdr"
license:             BSD3
author:              "u2x1"
maintainer:          "u2x1@outlook.com"
copyright:           "2020-2026 u2x1"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/u2x1/gcwdr#readme>

language: GHC2021

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.18 && < 5
- array
- attoparsec
- bytestring
- text
- containers
- time
- directory
- extra
- network
- optparse-applicative
- html-entities
- stringsearch
- process
- toml-parser
- filepath
- fsnotify
- scotty
- wai-extra
- aeson
- http-types
- random
- skylighting
- blaze-html

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gcwdr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gcwdr
    when:
    - condition: false
      other-modules: Paths_gcwdr

tests:
  gcwdr-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gcwdr
    - hspec
    - hspec-discover
    - QuickCheck
