name:                gcwdr
version:             0.1.0.0
github:              "Nutr1t07/gcwdr"
license:             BSD3
author:              "Nutr1t07"
maintainer:          "nutr1t07@outlook.com"
copyright:           "2020 Nutr1t07"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nutr1t07/gcwdr#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring
- containers
- time
- word8
- directory
- utf8-string
- extra

library:
  source-dirs: src

executables:
  gcwdr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gcwdr

tests:
  gcwdr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gcwdr
