name:                gcwdr
version:             0.1.0.0
github:              "Nutr1t07/gcwdr"
license:             BSD3
author:              "Nutr1t07"
maintainer:          "nutr1t07@outlook.com"
copyright:           "2020 Nutr1t07"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nutr1t07/gcwdr#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring
- text
- containers
- time
- word8
- directory
- utf8-string
- extra
- network
- html-entities
- QuickCheck
- hspec
- hspec-discover
- stringsearch
- process
- tomland
- filepath
- fsnotify
- scotty
- aeson
- http-types
- filemanip

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gcwdr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gcwdr
    when:
    - condition: false
      other-modules: Paths_gcwdr

tests:
  gcwdr-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gcwdr
